# A Secret is an object used to store sensitive data such as: Passwords, API keys, Tokens. These are meant for confidential information.
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
# Values are base64-encoded
data:
  username: "YWRtaW4K"
  password: "YWRtaW4xMgo="